/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#ifndef __cplusplus
#error This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
#endif

// Avoid multiple includes of Amply symbols
#ifndef Amply_H
#define Amply_H

#import <Foundation/Foundation.h>
#import <RCTRequired/RCTRequired.h>
#import <RCTTypeSafety/RCTConvertHelpers.h>
#import <RCTTypeSafety/RCTTypedModuleConstants.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTCxxConvert.h>
#import <React/RCTManagedPointer.h>
#import <ReactCommon/RCTTurboModule.h>
#import <optional>
#import <vector>


NS_ASSUME_NONNULL_BEGIN
namespace JS {
  namespace NativeAmplyModule {
    struct AmplyInitializationConfig {
      NSString *appId() const;
      NSString *apiKeyPublic() const;
      NSString *apiKeySecret() const;
      NSString *endpoint() const;
      id<NSObject> _Nullable datasetPrefetch() const;
      NSString *defaultConfig() const;

      AmplyInitializationConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeAmplyModule_AmplyInitializationConfig)
+ (RCTManagedPointer *)JS_NativeAmplyModule_AmplyInitializationConfig:(id)json;
@end
namespace JS {
  namespace NativeAmplyModule {
    struct TrackEventPayload {
      NSString *name() const;
      id<NSObject> _Nullable properties() const;

      TrackEventPayload(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeAmplyModule_TrackEventPayload)
+ (RCTManagedPointer *)JS_NativeAmplyModule_TrackEventPayload:(id)json;
@end
@protocol NativeAmplyModuleSpec <RCTBridgeModule, RCTTurboModule>

- (void)initialize:(JS::NativeAmplyModule::AmplyInitializationConfig &)config
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject;
- (NSNumber *)isInitialized;
- (void)track:(JS::NativeAmplyModule::TrackEventPayload &)payload
      resolve:(RCTPromiseResolveBlock)resolve
       reject:(RCTPromiseRejectBlock)reject;
- (void)getRecentEvents:(double)limit
                resolve:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject;
- (void)getDataSetSnapshot:(NSDictionary *)type
                   resolve:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject;
- (void)registerDeepLinkListener;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;

@end

@interface NativeAmplyModuleSpecBase : NSObject {
@protected
facebook::react::EventEmitterCallback _eventEmitterCallback;
}
- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper;

- (void)emitOnSystemEvent:(NSDictionary *)value;
- (void)emitOnDeepLink:(NSDictionary *)value;
@end

namespace facebook::react {
  /**
   * ObjC++ class for module 'NativeAmplyModule'
   */
  class JSI_EXPORT NativeAmplyModuleSpecJSI : public ObjCTurboModule {
  public:
    NativeAmplyModuleSpecJSI(const ObjCTurboModule::InitParams &params);
  };
} // namespace facebook::react
inline NSString *JS::NativeAmplyModule::AmplyInitializationConfig::appId() const
{
  id const p = _v[@"appId"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeAmplyModule::AmplyInitializationConfig::apiKeyPublic() const
{
  id const p = _v[@"apiKeyPublic"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeAmplyModule::AmplyInitializationConfig::apiKeySecret() const
{
  id const p = _v[@"apiKeySecret"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeAmplyModule::AmplyInitializationConfig::endpoint() const
{
  id const p = _v[@"endpoint"];
  return RCTBridgingToOptionalString(p);
}
inline id<NSObject> _Nullable JS::NativeAmplyModule::AmplyInitializationConfig::datasetPrefetch() const
{
  id const p = _v[@"datasetPrefetch"];
  return p;
}
inline NSString *JS::NativeAmplyModule::AmplyInitializationConfig::defaultConfig() const
{
  id const p = _v[@"defaultConfig"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeAmplyModule::TrackEventPayload::name() const
{
  id const p = _v[@"name"];
  return RCTBridgingToString(p);
}
inline id<NSObject> _Nullable JS::NativeAmplyModule::TrackEventPayload::properties() const
{
  id const p = _v[@"properties"];
  return p;
}
NS_ASSUME_NONNULL_END
#endif // Amply_H
