
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package tools.amply.sdk.reactnative;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeAmplyModuleSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "Amply";

  public NativeAmplyModuleSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  protected final void emitOnSystemEvent(ReadableMap value) {
    mEventEmitterCallback.invoke("onSystemEvent", value);
  }

  protected final void emitOnDeepLink(ReadableMap value) {
    mEventEmitterCallback.invoke("onDeepLink", value);
  }

  @ReactMethod
  @DoNotStrip
  public abstract void initialize(ReadableMap config, Promise promise);

  @ReactMethod(isBlockingSynchronousMethod = true)
  @DoNotStrip
  public abstract boolean isInitialized();

  @ReactMethod
  @DoNotStrip
  public abstract void track(ReadableMap payload, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getRecentEvents(double limit, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getDataSetSnapshot(ReadableMap type, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void registerDeepLinkListener();

  @ReactMethod
  @DoNotStrip
  public abstract void addListener(String eventName);

  @ReactMethod
  @DoNotStrip
  public abstract void removeListeners(double count);
}
